all: subsystems
	
subsystems:
	@cd Binary\ Trees && $(MAKE)
	@cd BitFields && $(MAKE)
	@cd C\ Run\ Time && $(MAKE)
	@cd Database && $(MAKE)
	@cd Examples && $(MAKE)
	@cd Function\ Prototypes && $(MAKE)
	@cd Preprocessor && $(MAKE)
	@cd Spreadsheet && $(MAKE)
	

clean:
	@cd Binary\ Trees && $(MAKE) clean
	@cd BitFields && $(MAKE) clean
	@cd C\ Run\ Time && $(MAKE) clean
	@cd Database && $(MAKE) clean
	@cd Examples && $(MAKE) clean
	@cd Function\ Prototypes && $(MAKE) clean
	@cd Preprocessor && $(MAKE) clean
	@cd Spreadsheet && $(MAKE) clean


